// File generated by FlutterFire CLI.
// TODO: Run `flutterfire configure` to generate this file with your Firebase project details.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDtsXnqHav0_VgNZNHR0tFbAuofjiQiG4',
    appId: '1:148376111214:android:7e095160708db47edd3e7f',
    messagingSenderId: '148376111214',
    projectId: 'ribal-4ac8c',
    storageBucket: 'ribal-4ac8c.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase project configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK-EK_guRZ5AtrrPGU33HNPpcFOqlSFXE',
    appId: '1:148376111214:ios:7d7eace3f25f15f1dd3e7f',
    messagingSenderId: '148376111214',
    projectId: 'ribal-4ac8c',
    storageBucket: 'ribal-4ac8c.firebasestorage.app',
    iosBundleId: 'com.ribal.tasks',
  );

  // TODO: Replace with your actual Firebase project configuration
}